Traceback (most recent call last):
  File "/Users/laurac/opt/anaconda3/envs/cc_indicators/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/laurac/opt/anaconda3/envs/cc_indicators/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/laurac/opt/anaconda3/envs/cc_indicators/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/laurac/opt/anaconda3/envs/cc_indicators/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/laurac/opt/anaconda3/envs/cc_indicators/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/laurac/opt/anaconda3/envs/cc_indicators/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/laurac/opt/anaconda3/envs/cc_indicators/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(figsize = (15, 5))
ax2 = ax.twinx()
colors = cm.rainbow(np.linspace(0, 1, len(range(1985, 2025))))
lw = 1
alpha = 0.1

for iy, y in enumerate(range(1985, 2025)):

    data_plot = data_crw.loc[f'{y}']

    ax.plot(data_plot.index.dayofyear, data_plot['SST@90th_HS'],color = colors[iy], alpha = alpha, label = 'SST', lw = lw)

    ax2.plot(data_plot.index.dayofyear, data_plot['DHW_from_90th_HS>1'],color = colors[iy], alpha = alpha, label = 'SST', lw = lw)
    ax2.fill_between(data_plot.index.dayofyear, 0, data_plot['DHW_from_90th_HS>1'],color = colors[iy], alpha = .1, label = 'SST')

    lw +=.015
    alpha +=.008

ax.set_ylim(20, 32)
ax.set_ylabel('SST (Â°C)', fontsize = 14, color = 'darkgreen')
ax.set_xlabel('Date', fontsize = 14)
ax2.set_ylabel('DHW', fontsize = 14, color = 'darkred')
ax2.set_xlim(0, 365)
ax2.set_ylim(0, 15)

cbar = plt.colorbar(cm.ScalarMappable(cmap=cm.rainbow), ax = ax)
cbar.set_label('Year', fontsize = 14)
cbar.set_ticks([0, 1])
cbar.set_ticklabels(['1985', '2024'])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[9], line 3[0m
[1;32m      1[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots(figsize [38;5;241m=[39m ([38;5;241m15[39m, [38;5;241m5[39m))
[1;32m      2[0m ax2 [38;5;241m=[39m ax[38;5;241m.[39mtwinx()
[0;32m----> 3[0m colors [38;5;241m=[39m [43mcm[49m[38;5;241m.[39mrainbow(np[38;5;241m.[39mlinspace([38;5;241m0[39m, [38;5;241m1[39m, [38;5;28mlen[39m([38;5;28mrange[39m([38;5;241m1985[39m, [38;5;241m2025[39m))))
[1;32m      4[0m lw [38;5;241m=[39m [38;5;241m1[39m
[1;32m      5[0m alpha [38;5;241m=[39m [38;5;241m0.1[39m

[0;31mNameError[0m: name 'cm' is not defined

